paths:
  data_raw: "data/raw"
  data_processed: "data/processed"
  data_external: "data/external"
  models_dir: "models"
  outputs_dir: "outputs"

onemap:
  base_url: "https://www.onemap.gov.sg/api/common/elastic/search"

geography:
  cbd_lat: 1.283933
  cbd_lng: 103.852222  # Raffles Place

mrt:
  stations_csv: "data/external/mrt_stations.csv"

loan:
  hdb_rate: 0.026
  bank_rate: 0.040
  hdb_ltv: 0.75
  bank_ltv: 0.75
  hdb_min_cash_downpayment_pct: 0.00
  bank_min_cash_downpayment_pct: 0.05

affordability:
  msr_limit: 0.30
  tdsr_limit: 0.55

bsd:
  tiers:
    - amount: 180000
      rate: 0.01
    - amount: 180000
      rate: 0.02
    - amount: 640000
      rate: 0.03
    - amount: 500000
      rate: 0.04
    - amount: 999999999
      rate: 0.05
