/**
 * ST7 Home / report station (README_XCH §7.3 ST7 / §8 S2 task 4). S2 scope:
 * styled report generator + Responsible AI disclosure cards + footer credit.
 * The "train arrives home, door opens, planet lights up" scroll sequence
 * (§7.11.2) is S3's job — this station is static here.
 *
 * The bonus fireworks image (clips/Ending.png -> static/img/fireworks.png) is
 * an easter egg addition, not a replacement for the §7.11.2 planet ending —
 * XCH's explicit call after reviewing it mid-S2 (2026-07-17): keep it tucked
 * behind a quiet "One more thing" disclosure so it doesn't compete with the
 * planned close.
 */
import { journeyState } from "../state.js";
import { TemplateProvider } from "../report/providers.js";
import { renderMarkdown } from "../markdown.js";

const DISCLOSURES = [
  {
    title: "Not a licensed valuation",
    body: "HDBrain is a statistical estimate from historical resale transactions, not a professional appraisal or a substitute for one.",
  },
  {
    title: "Training data ends in 2023",
    body: "The CPI series used to inflation-adjust prices freezes after 2020-09, so estimates run 9–16% below real 2025 transactions during this upside market.",
  },
  {
    title: "Prediction intervals are optimistic",
    body: "The 90% interval's measured coverage on 2024–2026 data is well below 90% — see the Model Arena for the exact figures.",
  },
  {
    title: "Icons are schematic, not photos",
    body: "Flat-model silhouettes and the town map represent categories, not the specific unit or building you searched for.",
  },
  {
    title: "Built to degrade gracefully",
    body: "This report is generated by a deterministic, zero-dependency template. An optional local-LLM writer can enhance the prose later without the product ever depending on it.",
  },
];

// Ordered alphabetically by surname (Lin, Xu, Zhang, Zhao) — noted explicitly
// on the page per XCH's ask (2026-07-17), since it's not the order she first
// listed the names in and the page should say so rather than leave it to guess.
const TEAM = [
  { name: "Lin Hali", school: "ZJU" },
  { name: "Xu Chuhao", school: "UIUC" },
  { name: "Zhang Zherui", school: "UIUC" },
  { name: "Zhao Hongshuo", school: "ZJU" },
];

export function initSt7() {
  const root = document.getElementById("st7-home");
  if (!root) return;

  root.innerHTML = `
    <div class="station-inner">
      <h2>ST7 &middot; Home</h2>
      <p class="lede">Everything you checked this session, assembled into one report.</p>

      <div class="card glass st7-report-card">
        <div class="cluster">
          <button type="button" id="st7-generate">Generate my report</button>
          <button type="button" class="btn-ghost btn-sm" id="st7-download" hidden>Download as Markdown</button>
        </div>
        <div id="st7-report" class="st7-report-body"></div>
      </div>

      <h3>Responsible AI</h3>
      <div class="grid-cards grid-cards-5">
        ${DISCLOSURES.map((d) => `
          <div class="card">
            <h3>${d.title}</h3>
            <p>${d.body}</p>
          </div>`).join("")}
      </div>

      <details class="one-more-thing">
        <summary>One more thing</summary>
        <figure>
          <img src="./static/img/fireworks.png" alt="A couple watching National Day fireworks over Marina Bay, illustrating the journey's end." />
          <figcaption>Wei Ling &amp; Marcus, somewhere past the last station.</figcaption>
        </figure>
      </details>

      <footer class="st7-footer">
        <p class="disclosure">Data: data.gov.sg HDB resale flat prices. Policy references: MAS, MoneySense.
           Built for an NUS course project.</p>
        <h3>Team</h3>
        <ul class="team-list">
          ${TEAM.map((m) => `<li>${m.name} <span class="team-school">(${m.school})</span></li>`).join("")}
        </ul>
        <p class="disclosure">Listed alphabetically by surname.</p>
        <div class="cluster">
          <a class="btn-ghost btn-sm" href="https://github.com/hasson827/HDBrain" target="_blank" rel="noopener">GitHub</a>
          <a class="btn-ghost btn-sm" href="#st0-departure">Back to the top &uarr;</a>
        </div>
      </footer>
    </div>
  `;

  let lastMarkdown = "";
  document.getElementById("st7-generate").addEventListener("click", () => {
    const provider = new TemplateProvider();
    lastMarkdown = provider.generate(journeyState);
    document.getElementById("st7-report").innerHTML = renderMarkdown(lastMarkdown);
    document.getElementById("st7-download").hidden = false;
  });

  document.getElementById("st7-download").addEventListener("click", () => {
    const blob = new Blob([lastMarkdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "hdbrain-report.md";
    a.click();
    URL.revokeObjectURL(url);
  });
}
